# Generated by Django 3.2.5 on 2022-09-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DongSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(choices=[('Mypham', 'Mỹ phẩm'), ('Tuixach', 'Túi xách'), ('Quanao', 'Quần áo')], max_length=50)),
                ('Ten_Tieng_Viet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(choices=[('Balo', 'Ba lô'), ('Kem', 'Kem'), ('Son', 'Son'), ('Nuochoa', 'Nước hoa'), ('Quan', 'Quần'), ('Ao', 'Áo'), ('PhanTrangDiem', 'Phấn trang điểm')], max_length=50)),
                ('Ten_Tieng_Viet', models.CharField(max_length=50)),
                ('Dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.dongsanpham')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=50)),
                ('Gia_ban_dau', models.IntegerField(default=200000)),
                ('Gia_giam', models.IntegerField(default=1000000)),
                ('Mo_ta_san_pham', models.TextField(default='Kem tri nam')),
                ('Anh_san_pham', models.ImageField(upload_to='pictures/')),
                ('Loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.loaisanpham')),
            ],
        ),
    ]
